version: '3.8'

services:

    db:
       image: postgres:16
       container_name: postgres_db
       environment:
            POSTGRES_USER: britsh
            POSTGRES_PASSWORD: british@2025
            POSTGRES_DB: bd_ocorrencias
       ports:
            - "5432:5432"
       volumes:
            - postgres_data:/var/lib/postgresql/data
       networks:
            - my_network

volumes:
    postgres_data:
    
networks:
     my_network:
         driver: bridge